name: Deploy App

on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: setup node
      uses: actions/setup-node@v1
      with:
        node-version: '18.x'

    # package.jsonに基づき依存パッケージをインストールする
    # それほど遅くないのでキャッシュはしない
    - name: install
      run: yarn --frozen-lockfile

    # Next.jsアプリをビルド
    - name: build
      run: yarn build

    # nojekyllを追加、リソースを読み込めるように
    - name: add nojekyll
      run: touch ./out/.nojekyll

    - name: deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: out
        # docsを削除しない
        clean-exclude: /docs/
